### ISSUE TITLE
TodoViewModel does not await `async LoadTodos`

### ISSUE THREAD

**Issue by gentledepp** [eszterhorvath/ToDo#1]
Please
- [x] have a look at how "initialize" can be used to execute any async code in a MvvmCross viewmodel
- [x] refactor the viewmodel to only load tasks in its "initialize" method - the constructor is only there for taking in dependencies

**Comment by eszterhorvath** [comment]
I refactored the ToDoViewModel code, i added Initialize method to load data there.
Commit: 6eb78f68731412db22d093e571b3da1fa4a56931
