### ISSUE TITLE
TodoViewModel - not using ObservableCollection

### ISSUE THREAD

**Issue by gentledepp** [eszterhorvath/ToDo#2]
your `_todos` are just a simple list.
Please use an `ObservableCollection<Todo>` instead.
Those collections are build for the purpose to be data-bound to the UI: They can notify the UI whenever an item is added or removed, so that it stays in sync!
A simple "List<Todo>" does not do this :-)

**Comment by eszterhorvath** [comment]
The above referenced commit was a mistake made during rebasing. Please ignore it.
