### ISSUE TITLE
TodoView uses code-behind `OnButtonClicked`

### ISSUE THREAD

**Issue by gentledepp** [eszterhorvath/ToDo#3]
Please remove te code-behind of your TodoVIew. Using code behind should *always* be your last resort as it is hard to impossible to test it!

- [x] Create a `AddTodoItemCommand` (Please no "ButtonClicked" namings!) in your `TodoViewModel` and bind it to your buttons `Command` property
- [x] This command should use the `IMvxNavigationService` to navigate to the `AddViewModel` 
- [x] write a simple unit test for this! (Think about what can be tested)

**Comment by eszterhorvath** [comment]
I refactored the navigation between ToDoViewModel and AddViewModel using Command and not code-behind. I'll add unit tests soon!

**Comment by eszterhorvath** [comment]
I added unit test. (Commit: 04a95b9b850b6a350009cfc84ea4183bcc732e70)
