### ISSUE TITLE
TodoView uses code-behind `OnItemSelected`

### ISSUE THREAD

**Issue by gentledepp** [eszterhorvath/ToDo#4]
- [x] Rather than using the event `ItemSelected`, use a two-way binding to bind your `ListView.SelectedItem` property to the `ToDoViewModel`
- [x] think about how you can handle async behavior now - because the binding will only update a `SelectedTodo` property of your ViewModel and property setters cannot be asynchronous!
- [x] use a service to request the users confirmation. E.g. [acr.userdialogs](https://devlinduldulao.pro/how-to-use-acr-userdialogs/)
- [x] selecting an item should not remove it, but open a `EditViewModel`! 
- [x] --> think about what user gesture *should* be used to actually delete an item. Let me know your thoughts
- [x] write a unit test, that shows that if an item is about to be removed and the user accepts/rejects the confirmation, the item is deleted/not deleted

**Comment by eszterhorvath** [comment]
I've been rethinking how to handle user interactions.

If the user selects an item, the state of the item will change (Pending -> Done / Done -> Pending).
With the swipe gesture, the user can select 'Delete' or 'Edit'.
I used Acr.Userdialogs to show alert/confirm dialogs (eg. deleting an item or adding an item without title).
I added unit tests too.

EditViewModel: #11
